
# html lang
language: zh-cn

# main menu navigation
menu:
  About: /about
  Resume: /resume
  Archives: /archives

# stylesheets 
stylesheets:
- /css/sprinter.css
# TODO 外部依赖
- //at.alicdn.com/t/font_1464257_drr710yuepc.css
- //cdn.bootcss.com/font-awesome/5.10.2/css/all.min.css

# scripts 
scripts:
# TODO 外部依赖
- //cdn.bootcss.com/jquery/3.4.1/jquery.min.js
- /js/sprinter.js


mathjax:
  enable: true
  src: '//cdn.bootcss.com/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
  
