
# html lang
language: zh-cn

# main menu navigation
menu:
  About: /about
  Resume: /resume
  Archives: /archives

# stylesheets 
stylesheets:
# - https://cdnjs.cloudflare.com/twitter-bootstrap/4.3.1/css/bootstrap-reboot.min.css
# - https://cdnjs.cloudflare.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css
# - https://cdnjs.cloudflare.com/animate.css/3.7.0/animate.min.css
# - https://cdnjs.cloudflare.com/bootstrap-material-design/4.0.2/bootstrap-material-design.min.css
- /css/sprinter.css
# - /css/monokai.css
# TODO 外部依赖
- //at.alicdn.com/t/font_1464257_drr710yuepc.css
- //cdn.bootcss.com/font-awesome/5.10.2/css/all.min.css
# - /assets/prism.css






# scripts 
scripts:
# - https://cdnjs.cloudflare.com/jquery/3.4.1/jquery.slim.min.js
# - https://cdnjs.cloudflare.com/popper.js/1.15.0/umd/popper.min.js
# - https://cdnjs.cloudflare.com/lodash.js/4.17.11/lodash.min.js
# - https://cdnjs.cloudflare.com/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js
# - https://cdnjs.cloudflare.com/bootstrap-material-design/4.0.2/bootstrap-material-design.umd.min.js
# TODO 外部依赖
- //cdn.bootcss.com/jquery/3.4.1/jquery.min.js
# - //cdn.bootcss.com/mathjax/2.7.6/MathJax.js
- /js/sprinter.js
# - /assets/prism.js


mathjax:
  enable: true
  src: '//cdn.bootcss.com/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
  # cdn: //cdn.bootcss.com/mathjax/2.7.6/MathJax.js
  
